#!/bin/bash

for infile in "$@"; do
    ofile=$(echo $infile | sed 's|src/\(.*\)\.[^\.]*|build/\1.o|')

    # Provided modules
    sed -n 's|^\s*module\s\+\(\S\+\)|\1.mod:'$ofile'|p' $infile
    
    # Used modules
    sed -n 's|^\s*use\s\+\([A-Za-z0-9_]\+\).*|'$ofile':\1.mod|p' $infile

done
